[project]
name = "clustering-tweets"
version = "0.1.0"
description = ""
authors = [
    {name = "Jacob Anderson",email = "jma195@case.edu"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "scikit-learn (>=1.8.0,<2.0.0)",
    "pandas (>=3.0.1,<4.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "kneed (>=0.8.6,<0.9.0)"
]

[tool.poetry]
packages = [{include = "clustering_tweets", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
